concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "sample-runner"
  url = "http://gitlab-server"
  token = "nf7NUC1kFHTeKHzLRh_z"
  executor = "docker"
  clone_url = "http://gitlab-server"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "game-of-life-ci-cd_default"
    shm_size = 0

[[runners]]
  name = "sample-runner"
  url = "http://gitlab-server"
  token = "B-KhnfAsXCapri2JyyyE"
  executor = "docker"
  clone_url = "http://gitlab-server"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "game-of-life-ci-cd_default"
    shm_size = 0

[[runners]]
  name = "sample-runner"
  url = "http://gitlab-server"
  token = "6heazBVT1cvkQZ9_9AwM"
  executor = "docker"
  clone_url = "http://gitlab-server"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "game-of-life-ci-cd_default"
    shm_size = 0
